name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ secrets.user }}
        password: ${{ secrets.CI_CD_PAT }}

    - name: Build the hello-world Docker image
      run: |
        docker pull mhart/alpine-node
        docker image tag mhart/alpine-node ghcr.io/Xcov19/alpine-mycovid:latest
        docker image push ghcr.io/Xcov19/alpine-mycovid:latest
